# Generated by Django 4.0.5 on 2022-06-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_booklog_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrowrequest',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
