# Generated by Django 4.0.5 on 2022-06-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_bookborrowrequest_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
