# Generated by Django 4.0.5 on 2022-06-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrowrequest',
            name='book_returned',
            field=models.BooleanField(default=False),
        ),
    ]
